apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: venk89/kub-data-demo:2
          env:
            - name: STORY_FOLDER
              # value: 'story'
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          # Volumes
          volumeMounts:
            - mountPath: /app/story
              name:
                story-volume
                # Volumes
      volumes:
        - name: story-volume
          # Persistent volume
          persistentVolumeClaim:
            claimName: host-pvc
